### ISSUE TITLE
rapidgenomics_cuda11.5.yml was wrong , and i fix some versions 冲突的内容太多了 不改装好后跑不起来

### ISSUE THREAD

**Issue by RaInSLc** [clara-parabricks/rapids-single-cell-examples#122]
rapidgenomics_cuda11.5.yml was wrong , and i fix some versions

冲突的内容太多了 不改装好后跑不起来

```yml
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.9
  - cudatoolkit=11.8
  - cuml=22.12.*
  - cudf=22.12.*
  - cugraph=22.12.*
  - cupy>=10.0.0
  - scanpy=1.9.1
  - python-wget
  - pybigwig
  - jupyterlab
  - ipykernel
  - wget
  - cmake
  - pip
  - pip:
    - jupyter-server-proxy
    - git+https://github.com/cjnolet/AtacWorks.git
```
